name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request: []
jobs:
  tests:
    runs-on: macOS-11.0
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Bootstrap
      run: ./script/bootstrap

    - name: Cleanup macOS
      run: |
        sudo rm -rf /usr/local/bin/brew /usr/local/.??* \
                    /usr/local/Homebrew \
                    /Applications/Xcode.app /usr/local/Caskroom \
                    /Library/Developer/CommandLineTools

    - name: Use newer Xcode
      run: sudo xcode-select --switch /Applications/Xcode_12.2.app/Contents/Developer

    - name: CI Tests
      run: ./script/cibuild
